baseURL = 'http://riggs.blog/'
languageCode = 'en-us'
title = 'The Riggs Blog'

theme = "nightfall"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[[params.social]]
key = 0
url = "https://gitlab.com/clerick_x"
icon = "fa fa-gitlab"

[[params.social]]
key = 1
url = "https://www.reddit.com/user/clerick_x"
icon = "fa fa-reddit"

[params]
author = "clerick_x"
user = "clerick_x"
hostname = "TheRiggsBlog"
description = "This is my personal website were i blog about stuff"

[markup.goldmark.renderer]
unsafe= true
